console.log('""+1+0',""+1+0)
console.log('""-1+0',""-1+0)
console.log('true+false',true+false)
console.log('6/"3"',6/"3")
console.log('"2"*"3"',"2"*"3")
console.log('null+1',null+1)
console.log('undefined+1',undefined+1)
